### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by az-iar** [az-iar/magento-billplz#2]
- [x] add order comment when updating payment status
- [ ] option to skip billplz bill
- [ ] cron task to delete overdue bills and cancel order
- [ ] support for magento 2
